### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by mamarilmanson** [flipcoder/qor#2]
There's no plan for an editor??? :)

**Comment by flipcoder** [comment]
I always wanted an editor in Qor.  There was a basic map editor in before the rewrite so it wouldn't be too hard to put something like that back in.  My artist works in Blender primarily so I want to get that support finished first and of course get some better documentation so people can learn how to use the engine without fumbling around with the code. :)

**Comment by mamarilmanson** [comment]
I'm sorry if this was an unnecessary issue and needs to be closed... this is the only way I know to contact you as soon as I found it...

would love to try how this would go about... I really like to learn python someday... this might be it... and more making a game out of it... I wish you can build an editor... and I would like to see it so I can(hope) I can contribute to it the earliest time possible... :)

**Comment by mamarilmanson** [comment]
and what about the gui? :)

**Comment by flipcoder** [comment]
No problem.  I'm glad you're interested! :)  The project is still in early stages as it's mainly a way for me to learn engine programming, so usage in a project at this point wouldn't be recommended unless the project is fairly simple.  There's definitely still bugs.  Of course, if you're not afraid to tweak the engine (and wanting to learn some engine coding as well) it would make a good game base/example to start with.  The python bindings are also not complete.  I've been looking for better ways to autogenerate the bindings instead of writing them manually in PythonBindings.h, but I haven't had a need for it yet.

I think if you just want to toy around with something for learning purposes you'll want to use something more stable like Ogre for the time being.  That way if you have bugs you'll know that they're your own and not just my engine's. ;)

There's no full GUI integration but I do support Cairo/Pango or using 2D ortho meshes and textures if you wanted to roll your own or integrate CEGUI.  I also have a basic game menu system that can be hooked up to game settings (see my qorpse project's MenuState for an example) if just want something quick.

Btw, you can always email me at flipcoder@gmail.com as well.   I'd be happy to answer more questions.

**Comment by mamarilmanson** [comment]
well... actually I'm more of a dev on top of something... like web dev... and game dev... not the backend/framework itself... that's where I don't excel in application but maybe in theory... like suggesting new features because I can't implement one and I don't because I want to focus on the previous topic I went about... 

as for a game engine... (honestly) I don't want to toy around with engine where scripting takes most of the time... I'm more of a WYSIWYG(unless maybe for webdev) guy... 

I do suggest you integrate a full GUI as most of the 3d engines I encounter(even when only for research purposes) doesn't have full GUI... they mostly rely on community built gui or a default gui with less customizability as the big guys has... so yeah... I suggest that and the editor... :)

oh and yeah... if I ever do suggest things... I always keep in mind that I suggest it considering the worst case scenario... like user irresponsibility I guess haha

(just letting you know... :) )

**Comment by flipcoder** [comment]
Thanks for the suggestions!  I'm working on 2 more demos which I'll have up soon w/ some physics integration so be sure to follow me to see the progress.

**Comment by mamarilmanson** [comment]
yeah sure... I already followed this repo... I might be writing suggestions... not to be done as of now... but will be handy in the future... :)

and as they say... may this be a start of a good relationship... _offers hand for a shakehand_

**Comment by mamarilmanson** [comment]
I don't want... intended... or in any way express you to be offended...

I want you to be inspired my friend... :)

http://xlgames-inc.github.io/posts/first/

**Comment by mamarilmanson** [comment]
I wonder... what if? what if??? you do the game editor with blender being the biggest influence? :D

**Comment by mamarilmanson** [comment]
Emailed you... :)

**Comment by mamarilmanson** [comment]
Emailed you again... :)

**Comment by mamarilmanson** [comment]
@flipcoder ~ Do you have a branding for this? I may want to put my designer skills into this one... :)

**Comment by flipcoder** [comment]
This is all I have so far, and it's just something I did myself in inkscape:
https://raw.githubusercontent.com/flipcoder/qor/master/bin/data/logo.png

If you wanna create one, go for it :)

**Comment by mamarilmanson** [comment]
@flipcoder ~ I've also sent you an email... a long one if you don't mind... 

I have a question... what's the story you might want to tell with the logo... or the impression you might want to express... that would be a starting point... :)
