### ISSUE TITLE
How to download and use?

### ISSUE THREAD

**Issue by Robotsrule4545** [flipcoder/qor#8]
How do you download and use this? BTW, I can't code like this. nice job!!!

**Comment by flipcoder** [comment]
Thanks for the interest.  This project hasn't been updated in a while so the direct link to the windows libraries apparently isn't up anymore, which I will fix.  I admit it's a bit difficult to build.  The easiest build process is on Linux, since you just have to grab each dependency and follow the instructions.  The hard one is Windows, which I can help you with if you're using that (manually building all the libs is VERY tricky, which is why you should instead download the libs as a pack manually from the link which I'll fix soon).  Also, this repository is just the base engine, so you'll want to build one of the demo games like https://github.com/flipcoder/game-off-2016 or https://github.com/flipcoder/microarmy so it'll actually run something instead of just being an empty starter template.

Note: It isn't a "modern" engine like Unity where the engine is separate from the game.  The engine and game code are compiled at the same time.

What OS are you wanting to build on?  I can give you more specific steps.

**Comment by flipcoder** [comment]
I should also mention my newer engine https://github.com/flipcoder/qork, which is a lot like Qor but written in python.  It's for smaller game projects and easier to use, but incomplete.

**Comment by Robotsrule4545** [comment]
Ah, windows 10?

**Comment by Robotsrule4545** [comment]
How do you build it from the empty template?

**Comment by flipcoder** [comment]
Here is the documentation and instructions:  https://github.com/flipcoder/qor/blob/master/QorBook.md

I updated the link to the libs package which was broken.
